#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Refactor calculateMonthlyCore + calculateMonthlyResult in App.tsx.
  - Core: structured object signature, pure (no master/row/settings)
  - Wrapper: resolves all inputs, passes structured object to core
"""

NBSP = b'\xc2\xa0 '  # U+00A0 + space = one indent level

def L(n, s=''):
    return NBSP * n + s.encode('utf-8') + b'\r'

E = b'\r'  # empty line

# ── calculateMonthlyCore ──────────────────────────────────────────────
core_lines = [
    L(0, 'const calculateMonthlyCore = ({'),
    L(1, 'basePay,'),
    L(1, 'allowanceAmounts,'),
    L(1, 'deductionAmounts,'),
    L(1, 'rates: { health: hRate, pension: pRate, nursing: nRate, childCare: cRate, employment: eRate },'),
    L(1, 'flags: { hasHealth, hasPension, hasEmployment, hasNursing, isDoubleSocialIns },'),
    L(1, 'tax: { dependents, isOtsu, taxCalcMethod, taxTables, yearStr },'),
    L(1, 'std: { stdAmount, standardRewardTable },'),
    L(0, '}) => {'),
    L(1, 'let totalAllowances = 0;'),
    L(1, 'let totalTaxableAllowances = 0;'),
    L(1, 'let totalSocialInsAllowances = 0;'),
    L(1, 'let totalEmploymentInsAllowances = 0;'),
    E,
    L(1, 'allowanceAmounts.forEach(({ amount, isTaxable, isSocialIns, isEmploymentIns }) => {'),
    L(2, 'totalAllowances += amount;'),
    L(2, 'if (isTaxable) totalTaxableAllowances += amount;'),
    L(2, 'if (isSocialIns) totalSocialInsAllowances += amount;'),
    L(2, 'if (isEmploymentIns) totalEmploymentInsAllowances += amount;'),
    L(1, '});'),
    E,
    L(1, 'const grossPay = basePay + totalAllowances;'),
    L(1, 'const taxableGross = basePay + totalTaxableAllowances;'),
    L(1, 'const socialInsGross = basePay + totalSocialInsAllowances;'),
    L(1, 'const employmentInsGross = basePay + totalEmploymentInsAllowances;'),
    E,
    L(1, 'const stdBase = socialInsGross;'),
    L(1, 'const estStdAmount ='),
    L(2, 'standardRewardTable?.length > 0'),
    L(3, '? getStandardRewardAmount(standardRewardTable, stdBase)'),
    L(3, ': stdBase;'),
    E,
    L(1, 'const employment = hasEmployment'),
    L(2, '? Math.floor(employmentInsGross * (eRate / 1000))'),
    L(2, ': 0;'),
    E,
    L(1, 'const stdAmountMissing = (hasHealth || hasPension) && stdAmount === null;'),
    L(1, 'if (stdAmountMissing) {'),
    L(2, 'return {'),
    L(3, 'grossPay,'),
    L(3, 'health: null,'),
    L(3, 'pension: null,'),
    L(3, 'nursing: null,'),
    L(3, 'childCare: null,'),
    L(3, 'employment: null,'),
    L(3, 'incomeTax: null,'),
    L(3, 'taxWarning: "標準報酬月額が未入力です",'),
    L(3, 'isBlocking: true,'),
    L(3, 'netPay: null,'),
    L(3, 'socialTotal: null,'),
    L(3, 'estStdAmount,'),
    L(3, 'totalCustomDeds: null,'),
    L(3, 'totalDeductions: null,'),
    L(3, 'calcSuccess: false,'),
    L(3, '_logData: {'),
    L(4, 'status: "stdAmountMissing",'),
    L(4, 'allowanceAmounts,'),
    L(4, 'socialInsGross,'),
    L(4, 'stdAmount,'),
    L(4, 'hRate, pRate, nRate, cRate, eRate,'),
    L(3, '},'),
    L(2, '};'),
    L(1, '}'),
    E,
    L(1, 'let gradeInfo = null;'),
    L(1, 'if (stdAmount !== null && stdAmount > 0 && estStdAmount > 0 && stdAmount !== estStdAmount) {'),
    L(2, 'const tbl = standardRewardTable?.length > 0 ? standardRewardTable : DEFAULT_STD_REWARD_TABLE;'),
    L(2, 'const getGrade = (amt) => { const r = tbl.find(tr => amt >= Number(tr.min) && amt < Number(tr.max)); return r ? Number(r.grade) : null; };'),
    L(2, 'const sGrade = getGrade(stdAmount);'),
    L(2, 'const eGrade = getGrade(estStdAmount);'),
    L(2, 'if (sGrade !== null && eGrade !== null) {'),
    L(3, 'gradeInfo = { sGrade, eGrade, gDiff: Math.abs(sGrade - eGrade), stdAmount, estStdAmount };'),
    L(2, '}'),
    L(1, '}'),
    E,
    L(1, 'const insMultiplier = isDoubleSocialIns ? 2 : 1;'),
    E,
    L(1, 'const ins = calculateSocialIns('),
    L(2, 'stdAmount ?? 0,'),
    L(2, '1,'),
    L(2, 'hRate,'),
    L(2, 'pRate,'),
    L(2, 'nRate,'),
    L(2, 'cRate,'),
    L(2, 'hasNursing'),
    L(1, ');'),
    E,
    L(1, 'if (!hasHealth || stdAmount == null || stdAmount === 0) {'),
    L(2, 'ins.health = 0;'),
    L(2, 'ins.nursing = 0;'),
    L(1, '} else {'),
    L(2, 'ins.health *= insMultiplier;'),
    L(2, 'ins.nursing *= insMultiplier;'),
    L(1, '}'),
    E,
    L(1, 'if (!hasPension || stdAmount == null || stdAmount === 0) {'),
    L(2, 'ins.pension = 0;'),
    L(2, 'ins.childCare = 0;'),
    L(1, '} else {'),
    L(2, 'ins.pension *= insMultiplier;'),
    L(2, 'ins.childCare *= insMultiplier;'),
    L(1, '}'),
    E,
    L(1, 'const socialTotal ='),
    L(2, 'ins.health + ins.pension + ins.nursing + ins.childCare + employment;'),
    E,
    L(1, 'const incomeTaxResult = calculateIncomeTax('),
    L(2, 'Math.max(0, taxableGross - socialTotal),'),
    L(2, 'dependents,'),
    L(2, 'isOtsu,'),
    L(2, 'false,'),
    L(2, 'null,'),
    L(2, '{ taxCalcMethod },'),
    L(2, 'yearStr,'),
    L(2, 'taxTables'),
    L(1, ');'),
    L(1, 'const incomeTax ='),
    L(2, 'typeof incomeTaxResult === "object" &&'),
    L(2, 'incomeTaxResult !== null &&'),
    L(2, 'incomeTaxResult.tax !== undefined'),
    L(3, '? incomeTaxResult.tax'),
    L(3, ': incomeTaxResult;'),
    E,
    L(1, 'const taxWarning ='),
    L(2, 'typeof incomeTaxResult === "object" &&'),
    L(2, 'incomeTaxResult !== null &&'),
    L(2, 'incomeTaxResult.warning !== undefined'),
    L(3, '? incomeTaxResult.warning'),
    L(3, ': null;'),
    E,
    L(1, 'const isBlocking ='),
    L(2, 'typeof incomeTaxResult === "object" &&'),
    L(2, 'incomeTaxResult !== null &&'),
    L(2, 'incomeTaxResult.isBlocking !== undefined'),
    L(3, '? incomeTaxResult.isBlocking'),
    L(3, ': false;'),
    E,
    L(1, 'const incomeTaxResultLog ='),
    L(2, 'typeof incomeTaxResult === "object" &&'),
    L(2, 'incomeTaxResult !== null &&'),
    L(2, 'incomeTaxResult.log'),
    L(3, '? incomeTaxResult.log'),
    L(3, ': [];'),
    E,
    L(1, 'if (incomeTax === null) {'),
    L(2, 'return {'),
    L(3, 'grossPay,'),
    L(3, 'health: null, pension: null, nursing: null, childCare: null,'),
    L(3, 'employment: null, socialTotal: null,'),
    L(3, 'incomeTax: null, totalDeductions: null, netPay: null,'),
    L(3, 'isBlocking: true,'),
    L(3, 'taxWarning: "計算条件不足のため処理を中断しました",'),
    L(3, 'calcSuccess: false,'),
    L(3, '_logData: {'),
    L(4, 'status: "incomeTaxNull",'),
    L(4, 'allowanceAmounts,'),
    L(4, 'socialInsGross,'),
    L(4, 'employmentInsGross,'),
    L(4, 'stdAmount,'),
    L(4, 'hRate, pRate, nRate, cRate, eRate,'),
    L(4, 'ins, employment, socialTotal,'),
    L(4, 'gradeInfo,'),
    L(4, 'incomeTaxResultLog,'),
    L(3, '},'),
    L(2, '};'),
    L(1, '}'),
    E,
    L(1, 'let totalCustomDeds = 0;'),
    L(1, 'deductionAmounts.forEach(({ amount }) => {'),
    L(2, 'totalCustomDeds += amount;'),
    L(1, '});'),
    E,
    L(1, 'return {'),
    L(2, 'grossPay,'),
    L(2, 'health: ins.health,'),
    L(2, 'pension: ins.pension,'),
    L(2, 'nursing: ins.nursing,'),
    L(2, 'childCare: ins.childCare,'),
    L(2, 'employment,'),
    L(2, 'incomeTax: incomeTax,'),
    L(2, 'taxWarning: taxWarning,'),
    L(2, 'isBlocking: isBlocking || incomeTax === null,'),
    L(2, 'socialTotal,'),
    L(2, 'estStdAmount: estStdAmount,'),
    L(2, 'totalCustomDeds,'),
    L(2, 'calcSuccess: true,'),
    L(2, '_logData: {'),
    L(3, 'status: "success",'),
    L(3, 'allowanceAmounts,'),
    L(3, 'deductionAmounts,'),
    L(3, 'socialInsGross,'),
    L(3, 'employmentInsGross,'),
    L(3, 'stdAmount,'),
    L(3, 'hRate, pRate, nRate, cRate, eRate,'),
    L(3, 'ins, employment, socialTotal,'),
    L(3, 'gradeInfo,'),
    L(3, 'incomeTaxResultLog,'),
    L(2, '},'),
    L(1, '};'),
    L(0, '};'),
]

# ── calculateMonthlyResult ────────────────────────────────────────────
result_lines = [
    L(0, 'const calculateMonthlyResult = (master, row, settings, monthKey, yearStr, taxTables = {}, monthlyLocks = {}) => {'),
    L(1, 'if (!master || !row) return {};'),
    E,
    L(1, 'const _lockYear = normalizeYear(yearStr);'),
    L(1, 'if (monthlyLocks?.[_lockYear]?.[monthKey]?.locked === true) {'),
    L(2, 'return {'),
    L(3, '...row,'),
    L(3, 'isLocked: true,'),
    L(3, 'isBlocking: true,'),
    L(3, 'lockMessage: "この月は全体ロック済です",'),
    L(3, 'grossPay: null,'),
    L(3, 'health: null,'),
    L(3, 'pension: null,'),
    L(3, 'nursing: null,'),
    L(3, 'childCare: null,'),
    L(3, 'employment: null,'),
    L(3, 'socialTotal: null,'),
    L(3, 'incomeTax: null,'),
    L(3, 'totalDeductions: null,'),
    L(3, 'netPay: null,'),
    L(3, 'calcSuccess: false,'),
    L(3, 'calcLog: ["この月は全体ロック済のため計算をスキップしました"],'),
    L(2, '};'),
    L(1, '}'),
    E,
    L(1, 'const allowanceDefs ='),
    L(2, 'settings?.allowanceDefinitions?.length > 0'),
    L(3, '? settings.allowanceDefinitions'),
    L(3, ': master.allowanceDefinitions || [];'),
    L(1, 'const deductionDefs ='),
    L(2, 'settings?.deductionDefinitions?.length > 0'),
    L(3, '? settings.deductionDefinitions'),
    L(3, ': master.deductionDefinitions || [];'),
    E,
    L(1, 'const allowanceAmounts = allowanceDefs.map((def) => ({'),
    L(2, '...def,'),
    L(2, 'amount: Number(row.allowanceAmounts?.[def.id]) || 0,'),
    L(1, '}));'),
    L(1, 'const deductionAmounts = deductionDefs.map((def) => ({'),
    L(2, '...def,'),
    L(2, 'amount: Number(row.deductionAmounts?.[def.id]) || 0,'),
    L(1, '}));'),
    E,
    L(1, 'const hRate = settings?.rateSchedules?.health'),
    L(2, '? getRateForMonth(settings.rateSchedules.health, monthKey)'),
    L(2, ': row.healthRate || 5.0;'),
    L(1, 'const pRate = settings?.rateSchedules?.pension'),
    L(2, '? getRateForMonth(settings.rateSchedules.pension, monthKey)'),
    L(2, ': row.pensionRate || 9.15;'),
    L(1, 'const nRate = settings?.rateSchedules?.nursing'),
    L(2, '? getRateForMonth(settings.rateSchedules.nursing, monthKey)'),
    L(2, ': row.nursingRate || 0.8;'),
    L(1, 'const cRate = settings?.rateSchedules?.childCare'),
    L(2, '? getRateForMonth(settings.rateSchedules.childCare, monthKey)'),
    L(2, ': row.childCareRate || 0.0;'),
    L(1, 'const eRate = settings?.rateSchedules?.employment'),
    L(2, '? getRateForMonth(settings.rateSchedules.employment, monthKey)'),
    L(2, ': row.employmentRate || 6.0;'),
    E,
    L(1, 'const hasHealth ='),
    L(2, 'master.healthIns !== undefined'),
    L(3, '? master.healthIns === 1'),
    L(3, ': master.socialIns === 1;'),
    L(1, 'const hasPension ='),
    L(2, 'master.pensionIns !== undefined'),
    L(3, '? master.pensionIns === 1'),
    L(3, ': master.socialIns === 1;'),
    L(1, 'const hasEmployment = master.employmentIns === 1;'),
    E,
    L(1, 'const stdAmountRaw = row.stdAmount;'),
    L(1, 'const stdAmount = (stdAmountRaw == null || stdAmountRaw === "")'),
    L(2, '? null'),
    L(2, ': Number(stdAmountRaw);'),
    E,
    L(1, 'const core = calculateMonthlyCore({'),
    L(2, 'basePay: Number(row.basePay) || 0,'),
    L(2, 'allowanceAmounts,'),
    L(2, 'deductionAmounts,'),
    L(2, 'rates: { health: hRate, pension: pRate, nursing: nRate, childCare: cRate, employment: eRate },'),
    L(2, 'flags: {'),
    L(3, 'hasHealth,'),
    L(3, 'hasPension,'),
    L(3, 'hasEmployment,'),
    L(3, 'hasNursing: row.hasNursingIns === 1,'),
    L(3, 'isDoubleSocialIns: !!row.isDoubleSocialIns,'),
    L(2, '},'),
    L(2, 'tax: {'),
    L(3, 'dependents: master.dependents,'),
    L(3, 'isOtsu: master.taxType === 1,'),
    L(3, 'taxCalcMethod: settings?.taxCalcMethod || "taxTable",'),
    L(3, 'taxTables,'),
    L(3, 'yearStr,'),
    L(2, '},'),
    L(2, 'std: {'),
    L(3, 'stdAmount,'),
    L(3, 'standardRewardTable: settings?.standardRewardTable,'),
    L(2, '},'),
    L(1, '});'),
    E,
    L(1, 'if (!core || !core._logData) return core ? { ...row, ...core } : {};'),
    E,
    L(1, 'const residentTax = Number(row.residentTax) || 0;'),
    L(1, 'const totalDeductions = core.incomeTax === null'),
    L(2, '? null'),
    L(2, ': (core.socialTotal ?? 0) + core.incomeTax + residentTax + (core.totalCustomDeds ?? 0);'),
    L(1, 'const netPay = totalDeductions === null ? null : (core.grossPay ?? 0) - totalDeductions;'),
    E,
    L(1, 'const ageAlerts = (yearStr && master?.dob)'),
    L(2, '? getAgeAlerts(master.dob, yearStr, monthKey)'),
    L(2, ': [];'),
    E,
    L(1, 'const { _logData, ...coreResult } = core;'),
    L(1, 'const result = { ...row, ...coreResult, totalDeductions, netPay };'),
    L(1, 'const logData = { ..._logData, ageAlerts };'),
    L(1, 'const { status } = logData;'),
    E,
    L(1, 'const calcLog = ["【月次給与 計算ログ】"];'),
    L(1, 'const base = Number(row.basePay) || 0;'),
    L(1, 'calcLog.push(`- 基本給: ${formatCurrency(base)}円`);'),
    E,
    L(1, '(logData.allowanceAmounts || []).forEach((def) => {'),
    L(2, 'if (def.amount > 0)'),
    L(3, 'calcLog.push('),
    L(4, '`  - 手当(${def.name}): ${formatCurrency(def.amount)}円 (課税:${def.isTaxable ? "〇" : "×"} / 社保:${def.isSocialIns ? "〇" : "×"})`'),
    L(3, ');'),
    L(1, '});'),
    E,
    L(1, 'calcLog.push(`- 総支給額: ${formatCurrency(result.grossPay)}円`);'),
    L(1, 'calcLog.push(`\\n【社会保険料】`);'),
    L(1, 'calcLog.push(`- 社保対象額(報酬月額): ${formatCurrency(logData.socialInsGross)}円`);'),
    L(1, 'calcLog.push(`- 適用標準報酬月額: ${logData.stdAmount === null ? "（未入力）" : formatCurrency(logData.stdAmount) + "円"}`);'),
    L(1, 'calcLog.push('),
    L(2, '`- 適用保険料率 (健保:${logData.hRate}% / 厚年:${logData.pRate}% / 介護:${logData.nRate}% / 支援金:${logData.cRate}% / 雇用:${logData.eRate}‰)`'),
    L(1, ');'),
    E,
    L(1, 'if (status === "stdAmountMissing") {'),
    L(2, 'calcLog.push(`⚠ 標準報酬月額が未入力です。社会保険料・所得税の計算を中断します。`);'),
    L(2, 'return { ...result, calcLog };'),
    L(1, '}'),
    E,
    L(1, 'if (logData.gradeInfo) {'),
    L(2, 'const { sGrade, eGrade, gDiff, stdAmount: sa, estStdAmount: ea } = logData.gradeInfo;'),
    L(2, 'if (gDiff >= 2) {'),
    L(3, 'calcLog.push(`⚠ 標準報酬月額（${formatCurrency(sa)}円/等級${sGrade}）と推定値（${formatCurrency(ea)}円/等級${eGrade}）の差が${gDiff}等級あります。届出内容を確認してください。`);'),
    L(2, '} else {'),
    L(3, 'calcLog.push(`△ 標準報酬月額（${formatCurrency(sa)}円）と推定値（${formatCurrency(ea)}円）に差異があります。`);'),
    L(2, '}'),
    L(1, '}'),
    E,
    L(1, 'if (row.isDoubleSocialIns)'),
    L(2, 'calcLog.push(`※ 退職時等：社保2ヶ月分徴収フラグON`);'),
    E,
    L(1, 'const logIns = logData.ins || {};'),
    L(1, 'calcLog.push(`  -> 健康保険料: ${formatCurrency(logIns.health ?? 0)}円`);'),
    L(1, 'calcLog.push(`  -> 厚生年金料: ${formatCurrency(logIns.pension ?? 0)}円`);'),
    L(1, 'if ((logIns.nursing ?? 0) > 0)'),
    L(2, 'calcLog.push(`  -> 介護保険料: ${formatCurrency(logIns.nursing)}円`);'),
    L(1, 'if ((logIns.childCare ?? 0) > 0)'),
    L(2, 'calcLog.push('),
    L(3, '`  -> 子ども・子育て支援金: ${formatCurrency(logIns.childCare)}円`'),
    L(2, ');'),
    L(1, 'calcLog.push('),
    L(2, '`  -> 雇用保険料: ${formatCurrency(logData.employment ?? 0)}円 (対象額:${formatCurrency(logData.employmentInsGross ?? 0)}円)`'),
    L(1, ');'),
    L(1, 'calcLog.push(`- 社会保険料合計: ${formatCurrency(logData.socialTotal ?? 0)}円\\n`);'),
    E,
    L(1, 'if (logData.incomeTaxResultLog?.length > 0) {'),
    L(2, 'calcLog.push(...logData.incomeTaxResultLog);'),
    L(1, '}'),
    E,
    L(1, 'if (status === "incomeTaxNull") {'),
    L(2, 'return { ...result, calcLog };'),
    L(1, '}'),
    E,
    L(1, 'calcLog.push(`- 住民税: ${formatCurrency(residentTax)}円`);'),
    E,
    L(1, '(logData.deductionAmounts || []).forEach((def) => {'),
    L(2, 'if (def.amount > 0) calcLog.push(`- 控除(${def.name}): ${formatCurrency(def.amount)}円`);'),
    L(1, '});'),
    E,
    L(1, 'calcLog.push(`\\n【支給結果】`);'),
    L(1, 'calcLog.push(`- 控除合計: ${result.totalDeductions === null ? "計算不可" : formatCurrency(result.totalDeductions)}円`);'),
    L(1, 'calcLog.push(`- 差引支給額: ${result.netPay === null ? "計算不可" : formatCurrency(result.netPay)}円`);'),
    E,
    L(1, 'if (logData.ageAlerts?.length > 0) {'),
    L(2, 'calcLog.push(`\\n【年齢到達アラート】`);'),
    L(2, 'logData.ageAlerts.forEach((a) => {'),
    L(3, 'if (a.type === "nursing40")'),
    L(4, 'calcLog.push('),
    L(5, '`- ${a.label}：介護保険料の徴収開始を確認してください。`'),
    L(4, ');'),
    L(3, 'if (a.type === "nursing65")'),
    L(4, 'calcLog.push('),
    L(5, '`- ${a.label}：介護保険料の給与控除終了を確認してください。`'),
    L(4, ');'),
    L(3, 'if (a.type === "pension70")'),
    L(4, 'calcLog.push('),
    L(5, '`- ${a.label}：厚生年金保険の資格喪失・70歳以上被用者該当届を確認してください。`'),
    L(4, ');'),
    L(3, 'if (a.type === "health75")'),
    L(4, 'calcLog.push('),
    L(5, '`- ${a.label}：健康保険資格喪失・後期高齢者医療制度への移行を確認してください。`'),
    L(4, ');'),
    L(2, '});'),
    L(1, '}'),
    E,
    L(1, 'return { ...result, calcLog };'),
    L(0, '};'),
]

# ── patch file ────────────────────────────────────────────────────────
PATH = r'c:/Users/h-miy/OneDrive/デスクトップ/アプリ/chingindaicho/src/App.tsx'

with open(PATH, 'rb') as f:
    raw = f.read()

lines = raw.split(b'\n')
print(f'Original lines: {len(lines)}')

# Replace result first (higher index), then core
lines[1312:1418] = result_lines
lines[1038:1311] = core_lines

print(f'New lines: {len(lines)}')

new_raw = b'\n'.join(lines)

# Safety: fix any bracket/char issues introduced by the Write tool
new_raw = new_raw.replace(b'\xe3\x80\x8c', b'\xe3\x80\x90')  # 「 -> 【
new_raw = new_raw.replace(b'\xe3\x80\x8d', b'\xe3\x80\x91')  # 」 -> 】
new_raw = new_raw.replace(b'\xe5\x8e\x98', b'\xe5\x8e\x9a')  # 厘 -> 厚
new_raw = new_raw.replace(b'\xe2\x97\x8b', b'\xe3\x80\x87')  # ○ -> 〇

with open(PATH, 'wb') as f:
    f.write(new_raw)

print('Done.')
